# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: kinopoisk
    ports: 
      - "5432:5432"
    